/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mongo;

import java.util.ArrayList;
import java.util.List;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import org.bson.Document;

public class HelloMongoDB {
    private static String uri = "mongodb+srv://username:IsxCSNkVExLp5zWi@free.jgtm2.mongodb.net/keyhole?retryWrites=true&w=majority";

    public boolean connect() {
        try (MongoClient mongoClient = MongoClients.create(uri)) {
            List<Document> databases = mongoClient.listDatabases().into(new ArrayList<>());
            databases.forEach(db -> System.out.println(db.toJson()));
        }
        return true;
    }
    public static void main(String[] args) {
        HelloMongoDB mongo = new HelloMongoDB();
        mongo.connect();
    }
}
