/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mongo;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelloMongoDBTest {
    @Test public void testAppHasAGreeting() {
        HelloMongoDB classUnderTest = new HelloMongoDB();
        assertTrue("app should have a greeting", classUnderTest.connect());
    }
}
